---
title: "Data Science HW 5"
author: "Hingling Yu"
date: "2023-11-08"
output: github_document
geometry: margin = 0.85in
fontsize: 12pt
---

```{r setup, include=FALSE}
library(tidyverse)
library(rvest)

knitr::opts_chunk$set(
	echo = TRUE,
	warning = FALSE
)

theme_set(theme_minimal() + theme(legend.position = "bottom"))

options(
  ggplot2.continuous.colour = "viridis",
  ggplot2.continuous.fill = "viridis"
)

scale_colour_discrete = scale_colour_viridis_d
scale_fill_discrete = scale_fill_viridis_d

set.seed(1)
```


## Problem 2


#### Use the `list.files` to create datafrane of file names
```{r, message = FALSE}
arms_df = 
  tibble(
    files = list.files(path = "data", full.names = TRUE)
    ) 
```

#### Data cleaning and tidying

```{r,message = FALSE}
tidy_arms_df = 
  arms_df %>% 
  mutate(
    participant_data = map(files, read_csv), # Read in each subject's data from the csv file
    arm_group = ifelse(str_detect(files, "exp"), "Experimental", "Control"), 
    # Determine the arm group from file name
    subject_id = as.factor(str_extract(files, "\\d+"))
  ) %>% 
  unnest(participant_data) %>%  # unnest the participant data into rows
  pivot_longer(
    week_1:week_8, 
    names_to = "week", 
    values_to = "measurements"
  ) %>% #transform the week columns into a "long" format
  mutate(week = parse_number(week)) # convert the week identifier to a numeric value
```

#### Spaghetti plot to visualize measurements for each participant across different time points

```{r}
tidy_arms_df %>%
  ggplot(
    aes(x = week, y = measurements, group = subject_id, color = subject_id)
    ) + # ensure lines are drawn for each subject
  geom_line(alpha = 0.6) + # set transparency to distinguish overlapping lines
  facet_wrap(.~ arm_group) + # use facet_wrap to separate the arm groups into different panels
  labs(
    title = "Participant Measurements Over the Study Period by arms group",
    subtitle = "Each line represents a single participant's measurements over time",
    x = "Week",
    y = "Measurement",
    color = "Subject ID"
  )
  
```

